"""Generated by nox session 'release' - do not edit by hand.

This module is rewritten on every executable generation. Source-only
runs therefore always see the last generated value.
"""

BUILD_NUMBER = 6
BUILD_DATETIME = "2026-10-05 13:51:54"
