"""Generic attribute generation step (random, manual or mixed)."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from functools import partial
from typing import Any, cast

from companion4soloplayer.core.creation.context import CharacterCreationContext, parse_path
from companion4soloplayer.core.creation.inputs import (
    InputField,
    InputKind,
    InputProvider,
    MissingInputError,
)
from companion4soloplayer.core.creation.steps.base import (
    CreationStep,
    StepConfigurationError,
)
from companion4soloplayer.core.creation.strategies import AttributeGenerationStrategy
from companion4soloplayer.core.dice_roller import DiceRoller

#: Generation modes understood by the step.
MODES: tuple[str, ...] = ("random", "manual", "mixed")


class AttributeGenerationStep(CreationStep):
    """Generate the base values of the character attributes.

    Three generation modes cover requirement "random draw **or** manual
    assignment (for all or part of the attributes)":

    - ``random``: every attribute is generated by the configured
      :class:`~companion4soloplayer.core.creation.strategies.AttributeGenerationStrategy`
      (resolved by name from ``context.system["strategies"]`` when a
      string is given), unless the provider already holds an answer for
      it (a die rolled in the Player dialog, a scripted fixture...);
    - ``manual``: every attribute is asked to the player
      (answer key ``<step_id>.<attribute>``);
    - ``mixed``: the attributes listed in ``manual_attributes`` are
      asked, the others are generated.

    The values are written as *base* values under ``target``; the
    bonuses and maluses granted by the rules are layered on top by the
    rules engine and read back with
    :meth:`CharacterCreationContext.effective`.

    Args:
        step_id: Unique identifier of the step.
        target: State path prefix storing the values (default
            ``values.attributes``).
        attributes: Explicit attribute names; when omitted the names
            are read from ``context.system["attributes"]`` (list or
            mapping keys).
        mode: ``random``, ``manual`` or ``mixed``.
        strategy: Strategy instance, strategy name (key of
            ``context.system["strategies"]``) or strategy class.
        manual_attributes: Attributes asked to the player in ``mixed``
            mode.
        min_value: Inclusive lower bound for manual answers and
            validation.
        max_value: Inclusive upper bound for manual answers and
            validation.
        roller: Optional dice roller (a fresh one is created per run).
        label: Human-readable label.

    Raises:
        StepConfigurationError: If ``step_id`` is empty, ``target`` is
            not a valid path, the mode is unknown or the bounds are
            inconsistent.

    Example:
        >>> from companion4soloplayer.core.creation.inputs import (
        ...     MappingInputProvider)
        >>> from companion4soloplayer.core.creation.strategies import (
        ...     ConstantStrategy)
        >>> step = AttributeGenerationStep(strategy=ConstantStrategy(12))
        >>> context = CharacterCreationContext(
        ...     system={"attributes": ["strength", "charm"]})
        >>> step.execute(context, MappingInputProvider({}))
        >>> context.get("values.attributes.charm")
        12
    """

    def __init__(
        self,
        step_id: str = "attributes",
        *,
        target: str = "values.attributes",
        attributes: Sequence[str] | None = None,
        mode: str = "random",
        strategy: AttributeGenerationStrategy | str | type | None = None,
        manual_attributes: Sequence[str] = (),
        min_value: int | None = None,
        max_value: int | None = None,
        roller: DiceRoller | None = None,
        label: str = "",
    ) -> None:
        """Initialize the step.

        Args:
            step_id: Unique identifier of the step.
            target: State path prefix storing the values.
            attributes: Explicit attribute names.
            mode: ``random``, ``manual`` or ``mixed``.
            strategy: Strategy instance, name or class.
            manual_attributes: Attributes asked in ``mixed`` mode.
            min_value: Inclusive lower bound.
            max_value: Inclusive upper bound.
            roller: Optional dice roller.
            label: Human-readable label.

        Raises:
            StepConfigurationError: If the configuration is invalid.
        """
        super().__init__(step_id, label=label)
        parse_path(target)
        if mode not in MODES:
            raise StepConfigurationError(
                f"Unknown attribute generation mode {mode!r} (available: {', '.join(MODES)})"
            )
        if min_value is not None and max_value is not None and min_value > max_value:
            raise StepConfigurationError(
                f"min_value ({min_value}) cannot be greater than max_value ({max_value})"
            )
        if attributes is not None:
            for position, attribute in enumerate(attributes):
                if not isinstance(attribute, str) or not attribute.strip():
                    raise StepConfigurationError(
                        f"Attribute #{position + 1} of step {step_id!r} must be a "
                        "non-empty string"
                    )
        self._target = target
        self._attributes = tuple(attributes) if attributes is not None else None
        self._mode = mode
        self._strategy = strategy
        self._manual_attributes = tuple(manual_attributes)
        self._min_value = min_value
        self._max_value = max_value
        self._roller = roller

    def attribute_names(self, context: CharacterCreationContext) -> list[str]:
        """Return the attribute names of the game system.

        Args:
            context: Current creation state.

        Returns:
            The explicit attribute names, else the names declared in
            ``context.system["attributes"]`` (list of names or mapping
            keys); an empty list when the system declares none.

        Raises:
            StepConfigurationError: If ``context.system["attributes"]``
                is neither a list of strings nor a mapping.
        """
        if self._attributes is not None:
            return list(self._attributes)
        raw = context.system.get("attributes")
        if raw is None:
            return []
        if isinstance(raw, Mapping):
            names: Any = list(raw.keys())
        elif isinstance(raw, Sequence) and not isinstance(raw, (str, bytes)):
            names = list(raw)
        else:
            raise StepConfigurationError(
                "system['attributes'] must be a list of names or a mapping, "
                f"got {type(raw).__name__}"
            )
        for position, name in enumerate(names):
            if not isinstance(name, str) or not name.strip():
                raise StepConfigurationError(
                    f"Attribute #{position + 1} of system['attributes'] must be a "
                    "non-empty string"
                )
        return list(names)

    def roll_attribute(
        self,
        attribute: str,
        context: CharacterCreationContext,
        roller: DiceRoller | None = None,
    ) -> int:
        """Generate one attribute value with the configured strategy.

        This is the public entry point used both by :meth:`execute`
        when the provider holds no answer, and by the die button of
        the Player dialog.

        Args:
            attribute: Attribute name to generate.
            context: Current creation state (resolves the named
                strategies of ``context.system["strategies"]``).
            roller: Optional dice roller (a fresh one is created when
                omitted).

        Returns:
            The generated base value.

        Raises:
            StepConfigurationError: If no strategy is configured, the
                name is unknown or the configured value is not an
                attribute strategy.
        """
        strategy = self._resolve_strategy(context)
        return strategy.roll(attribute, roller or DiceRoller())

    def describe_inputs(self, context: CharacterCreationContext) -> tuple[InputField, ...]:
        """Describe one field per attribute of the game system.

        A randomly generated attribute is a ``DICE`` field: the UI
        shows a label and a die button, and the rolled value becomes
        the answer kept by the step. A manually entered attribute is a
        ``NUMBER`` field (plain text entry).

        Args:
            context: Current creation state (provides the attribute
                names).

        Returns:
            One field per attribute, in declaration order; empty when
            the game system declares no attribute.

        Raises:
            StepConfigurationError: If ``context.system["attributes"]``
                is malformed.
        """
        fields: list[InputField] = []
        for attribute in self.attribute_names(context):
            manual = self._is_manual(attribute)
            roll = None if manual else partial(self.roll_attribute, attribute, context)
            fields.append(
                InputField(
                    key=f"{self.step_id}.{attribute}",
                    label=attribute,
                    kind=InputKind.NUMBER if manual else InputKind.DICE,
                    min_value=self._min_value,
                    max_value=self._max_value,
                    roll=roll,
                )
            )
        return tuple(fields)

    def is_applicable(self, context: CharacterCreationContext) -> bool:
        """Tell whether the step must run.

        Args:
            context: Current creation state.

        Returns:
            True when the game system declares at least one attribute.

        Raises:
            StepConfigurationError: If the system attribute declaration
                is malformed.
        """
        return bool(self.attribute_names(context))

    def execute(self, context: CharacterCreationContext, inputs: InputProvider) -> None:
        """Generate or ask every attribute value.

        Args:
            context: Current creation state, updated in place under
                ``target``.
            inputs: Answer source of the session.

        Raises:
            InputError: If an answer is out of bounds, or missing for a
                manual attribute.
            StepConfigurationError: If the system data or the strategy
                configuration is invalid.
        """
        names = self.attribute_names(context)
        if not names:
            return
        roller = self._roller or DiceRoller()
        for attribute in names:
            key = f"{self.step_id}.{attribute}"
            try:
                # A recorded answer (a die rolled by the Player dialog,
                # a scripted fixture...) wins over the strategy, which
                # stays the fallback producing the random value.
                value = inputs.ask_number(
                    key,
                    f"{attribute}",
                    minimum=self._min_value,
                    maximum=self._max_value,
                )
            except MissingInputError:
                if self._is_manual(attribute):
                    raise
                value = self.roll_attribute(attribute, context, roller)
            context.set(f"{self._target}.{attribute}", value)

    def validate(self, context: CharacterCreationContext) -> list[str]:
        """Validate the generated attribute values.

        Args:
            context: Current creation state.

        Returns:
            Error messages; empty when every attribute holds a valid
            integer within the configured bounds.
        """
        errors: list[str] = []
        try:
            names = self.attribute_names(context)
        except StepConfigurationError as exc:
            return [str(exc)]
        known = set(names)
        for attribute in self._manual_attributes:
            if attribute not in known:
                errors.append(f"Manual attribute {attribute!r} is not declared by the system")
        for attribute in names:
            path = f"{self._target}.{attribute}"
            if not context.has(path):
                errors.append(f"Missing value for attribute {attribute!r} ({path})")
                continue
            value = context.get(path)
            if not isinstance(value, int) or isinstance(value, bool):
                errors.append(
                    f"Attribute {attribute!r} must be an integer, got {type(value).__name__}"
                )
                continue
            if self._min_value is not None and value < self._min_value:
                errors.append(f"Attribute {attribute!r} must be >= {self._min_value}, got {value}")
            if self._max_value is not None and value > self._max_value:
                errors.append(f"Attribute {attribute!r} must be <= {self._max_value}, got {value}")
        return errors

    def _is_manual(self, attribute: str) -> bool:
        """Tell whether ``attribute`` is asked to the player.

        Args:
            attribute: Attribute name.

        Returns:
            True in ``manual`` mode, or in ``mixed`` mode when the
            attribute is listed in ``manual_attributes``.
        """
        if self._mode == "manual":
            return True
        if self._mode == "mixed":
            return attribute in self._manual_attributes
        return False

    def _resolve_strategy(self, context: CharacterCreationContext) -> AttributeGenerationStrategy:
        """Resolve the configured generation strategy.

        Args:
            context: Current creation state (provides the named
                strategies of ``context.system["strategies"]``).

        Returns:
            The strategy to use for the randomly generated attributes.

        Raises:
            StepConfigurationError: If no strategy is configured, the
                name is unknown, or the configured value is neither a
                strategy nor an instantiable class.
        """
        strategy: AttributeGenerationStrategy | str | type | None = self._strategy
        if strategy is None:
            raise StepConfigurationError(
                f"Step {self.step_id!r}: no attribute generation strategy configured"
            )
        if isinstance(strategy, str):
            registry = context.system.get("strategies", {})
            if not isinstance(registry, Mapping) or strategy not in registry:
                available = sorted(registry) if isinstance(registry, Mapping) else []
                raise StepConfigurationError(
                    f"Step {self.step_id!r}: unknown strategy {strategy!r} "
                    f"(available: {', '.join(available) or 'none'})"
                )
            strategy = registry[strategy]
        if isinstance(strategy, type):
            strategy_class = strategy
            try:
                strategy = strategy_class()
            except Exception as exc:
                raise StepConfigurationError(
                    f"Step {self.step_id!r}: cannot instantiate strategy "
                    f"{strategy_class.__name__}: {exc}"
                ) from exc
        if not callable(getattr(strategy, "roll", None)):
            raise StepConfigurationError(
                f"Step {self.step_id!r}: {strategy!r} is not an attribute strategy"
            )
        # The branches above exhaustively handled None, str and type, and
        # the roll attribute was just checked: the cast states that
        # guarantee without relying on the checker's narrowing.
        return cast(AttributeGenerationStrategy, strategy)
